steps:
  - command: |
      time npx -y supabase start
    plugins:
      - namespacelabs/nscache#v0.1:
          paths: ["~/.npm"]
    agents:
      nsc-cache-tag: buildkite-demo-cache-images/npm-cache
      nsc-experimental-containerd-cache-tag: buildkite-demo-cache-images/containerd-cache
      nsc-experimental-containerd-cache-size: 20g
